### ISSUE TITLE
Tiered nodes masternode cap

### ISSUE THREAD

**Issue by Quetio** [delionproject/Roadmaps#1]
I was looking at the Masternode Stats page, and particulary about the Masternodecap calculation.

I see that the masternodes projects with tiered Masternodes have there masternode cap calculated peer Tier.

I think that the masternode cap of one coin should be the total of value locked in all the tiers at one doesn't that would seems more coherent?

**Comment by delionproject** [comment]
![masternodecap](https://user-images.githubusercontent.com/43330417/152280601-7600d539-de81-4b12-8f32-01275437710a.PNG)
![masternodecap1](https://user-images.githubusercontent.com/43330417/152280608-85633924-3af4-439b-a1a4-db8e47ceeb29.PNG)

Request done.
